//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryContainer : DbContext
    {
        public LibraryContainer()
            : base("name=LibraryContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> EmployeeSet { get; set; }
        public virtual DbSet<Document> DocumentSet { get; set; }
        public virtual DbSet<Note> NoteSet { get; set; }
        public virtual DbSet<PeopleDocEntity> PeopleDocEntitySet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<EducationDirection> EducationDirectionSet { get; set; }
        public virtual DbSet<StudyGroup> StudyGroupSet { get; set; }
        public virtual DbSet<Department> DepartmentSet { get; set; }
    }
}
